### ISSUE TITLE
rendering a JSON response

### ISSUE THREAD

**Issue by raszi** [mutoh/gettext_rails#1]
I'm unable to render a JSON response from my controller, because every time when I try with 'render :json => result' I get the following error:

ActionView::MissingTemplate (Missing template offer/search_items_json.erb in view path app/views):
  /usr/lib/ruby/gems/1.8/gems/locale_rails-2.0.4/lib/locale_rails/action_view.rb:46:in `find_template'
  public/dispatch.fcgi:24

it looks like that the gettext is eating the :json parameter as it their parameter

**Comment by mutoh** [comment]
Could you send me the sample app which reproduce your problem?  I'm not good at json, and my simplest sample app(which I wrote) can't reproduce your problem

**Comment by raszi** [comment]
ohh, sorry it was a "premature return"
