### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by mytrile** [mutoh/gettext_rails#3]
I've install gettext_rails and the other gems, active record validation errors are translated, but distance_of_time_in_words gives me an error:

http://gist.github.com/133498

**Comment by barttenbrinke** [comment]
I have the same problem 2.0.1 works, 2.0.3 does not.

**Comment by mutoh** [comment]
Fixed. 
Thanks for reporting and sorry for late.

**Comment by mutoh** [comment]
And commited to github.
